sudo: false
services: mongodb
language: python
python:
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - DJANGO="Django>=2.0,<2.3"
  - DJANGO="Django>=3.0,<3.1"
before_install:
  - pip install poetry
install:
    - poetry install -q
    - poetry run pip install -q $DJANGO
# command to run tests
script: poetry run python setup.py -q nosetests
